### ISSUE TITLE
Thanks and a patch for rpm-repack

### ISSUE THREAD

**Issue by al-form2000** [cormander/rogue-beret-tools#2]
Greetings and thank you for the cool tool (rpm-repack). I found the following patch useful (add a --mkdir option, slightly improved reporting, vprints go to STDERR, use die rather than print/exit). I am appending this here because I am a github noob - there's got to be a better option.

    --- rpm-repack.orig	2013-06-07 09:52:08.430522430 +0200
    +++ rpm-repack	2013-06-07 09:51:20.852344955 +0200
    @@ -18,12 +18,14 @@
     
     my $dry_run = 0;
     my $verbose = 0;
    +my $mkdir   = 0;
     my $nop;
     
     my $getopt = GetOptions(
     	'dry-run' => \$dry_run,
     	'verbose' => \$verbose,
    -	'p' => \$nop,
    +        'mkdir'   => \$mkdir,
    +	'p'       => \$nop,
     );
     
     if (!$getopt) {
    @@ -48,8 +50,7 @@
     close RPM;
     
     if ($file_out =~ /is not installed/i) {
    -	print "The $rpm_pkg package is not installed\n";
    -	exit 1;
    +	die "The $rpm_pkg package is not installed\n";
     }
     
     #
    @@ -140,7 +141,7 @@
     
     Name: $rpm->{name}
     Version: $rpm->{version}
    -Release: $rpm->{release}
    +Release: $rpm->{release}RPCK
     Summary: $rpm->{summary}
     License: $rpm->{license}
     Distribution: $rpm->{distribution}
    @@ -227,16 +228,39 @@
     } else {
     
     	chomp(my $srcdir = `rpm --eval '%{_sourcedir}'`);
    -	chomp(my $specdir = `rpm --eval '%{_specdir}'`);
    -
    -	if (!$srcdir or ! -w $srcdir) {
    -		print "%{_sourcedir}: doesn't exist, or can't write to it\n";
    -		exit 1;
    +	if ( !-d $srcdir ) { 
    +	    if ($mkdir ) {
    +		#assumes unix-like, but hey, it's rpm anyway
    +		if ( system ("mkdir", "-p", "$srcdir") == 0) { 
    +		    vprint("Created $srcdir");
    +		} else {
    +		    die "%{_sourcedir}: mkdir -p $srcdir FAILED: $?";
    +		}
    +	    } else {
    +		die "%{_sourcedir}: $srcdir doesn't exist use --mkdir to fix\n";
    +	    }
    +	} elsif (!-w $srcdir) {
    +		die "%{_sourcedir}: $srcdir not writable\n";
    +	} elsif (!$srcdir) {
    +		die "%{_sourcedir}: rpm --eval '%{_sourcedir}' does not provide sourcedir\n";
     	}
     
    -	if (!$specdir or ! -w $specdir) {
    -		print "%{_specdir}: doesn't exist, or can't write to it\n";
    -		exit 1;
    +	chomp(my $specdir = `rpm --eval '%{_specdir}'`);
    +	if ( !-d $specdir ) { 
    +	    if ($mkdir ) {
    +		#assumes unix-like, but hey, it's rpm anyway
    +		if ( system ("mkdir", "-p", "$specdir") == 0) { 
    +		    vprint("Created $specdir");
    +		} else {
    +		    die "%{_sourcedir}: mkdir -p $specdir FAILED: $?";
    +		}
    +	    }  else {
    +		die "%{_specdir}: $specdir doesn't exist use --mkdir to fix\n";
    +	    }
    +	} elsif (!-w $specdir) {
    +		die "%{_sourcedir}: $srcdir not writable\n";
    +	} elsif (!$specdir) {
    +		die "%{_sourcedir}: rpm --eval '%{_sourcedir}' does not provide sourcedir\n";
     	}
     
     	&vprint("Unpacking $rpm_pkg");
    @@ -256,11 +280,11 @@
     sub usage {
     	my ($msg) = @_;
     	if ($msg) { print $msg, "\n"; }
    -	print "Usage: $0 pkg_name\n";
    +	print STDERR "Usage: $0 pkg_name\n";
     	exit 1;
     }
     
     sub vprint {
    -	print join("", @_), "\n" if $verbose;
    +	print STDERR join("", @_), "\n" if $verbose;
     }

**Comment by cormander** [comment]
Thanks. Please submit as a pull request.
